### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by TechieForFun** [swaggest/json-diff#27]
There are some deprecated dependencies like [codeclimate/php-test-reporter](https://github.com/codeclimate/php-test-reporter). 
Do you have plan to remove this in new version or updating other dependencies like phpunit version?

**Comment by vearutop** [comment]
Both 
```
    "phpunit/php-code-coverage": "2.2.4",
    "codeclimate/php-test-reporter": "^0.4.0"
```
can be removed, they are not actually needed for tests to run/report.

But `"phpunit/phpunit": "^4.8.23"` has to remain `^4` because `^5` does not support PHP 5.4 which is still supported by the lib.

**Comment by vearutop** [comment]
Fixed in https://github.com/swaggest/json-diff/pull/26.
