### ISSUE TITLE
Thank you 👍 

### ISSUE THREAD

**Issue by cavo789** [swaggest/json-diff#34]
I just want to thank you for `json-diff`, I was looking for such a tool to highlight what has been modified in a JSON file compared to an original file and, youhou!, `json-diff` does it perfectly. Thank you! Thank you very much!

For info, I've built a Powershell script based on your tool today: https://github.com/cavo789/json-tools

_Christophe_

**Comment by vearutop** [comment]
Thank you for using this library, I'm happy if it fits your needs. :)
