### ISSUE TITLE
Issue with comparing arrays

### ISSUE THREAD

**Issue by webpunk** [swaggest/json-diff#38]
Hi,

Sorry to bother you again. But when comparing two JSON objects, there is still a problem if the two contain an array whose contents are the same but do not appear in the same order in the array. Enclosed two JSON documents for testing.

Is there a chance to get a fix for this?

Thanks a lot
     Christian

[Archiv.zip](https://github.com/swaggest/json-diff/files/5386504/Archiv.zip)

**Comment by vearutop** [comment]
Please try [`v3.8.3`](https://github.com/swaggest/json-diff/releases/tag/v3.8.3), it now also checks hashes of non-scalar properties to use as rearrange base.
